site_name: Analytical Methods Vocabulary
site_url: https://katarinari.github.io/vocab_analyticalMethods/
site_description: Controlled vocabulary of analytical methods for chemical analysis in environmental monitoring samples

theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.top

docs_dir: docs

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - nl2br
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
