#!/usr/bin/env python3
"""
fix_tables.py
=============
Fixes <br/> tags inside Markdown table cells generated by LinkML gen-doc.
These tags break table rendering in MkDocs Material theme.

Usage:
    python3 scripts/fix_tables.py --dir docs
    python3 scripts/fix_tables.py --dir docs --verbose
"""

import argparse
import os
import re
from pathlib import Path


def fix_br_tags(docs_dir: str, verbose: bool = False):
    """
    Remove <br/> tags from inside Markdown table cells.

    Args:
        docs_dir: Path to the docs directory
        verbose: Print file names as they are processed
    """
    docs_path = Path(docs_dir)
    if not docs_path.exists():
        print(f"Error: directory not found: {docs_dir}")
        return 0

    fixed_count = 0
    file_count = 0

    for filepath in docs_path.rglob('*.md'):
        file_count += 1
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        # Replace <br/> inside table cells with a space
        new_content = re.sub(r'\s*<br/>\s*', ' ', content)

        if new_content != content:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(new_content)
            fixed_count += 1
            if verbose:
                print(f"  Fixed: {filepath}")

    print(f"Processed {file_count} files, fixed {fixed_count} files")
    return fixed_count


def main():
    parser = argparse.ArgumentParser(
        description='Fix <br/> tags in MkDocs Markdown table cells')
    parser.add_argument('--dir', '-d', default='docs',
                        help='Docs directory to process (default: docs)')
    parser.add_argument('--verbose', '-v', action='store_true',
                        help='Print file names as they are processed')
    args = parser.parse_args()

    fix_br_tags(args.dir, args.verbose)


if __name__ == '__main__':
    main()
